### ISSUE TITLE
Api error

### ISSUE THREAD

**Issue by Zvudkdn** [KiriXen/gogo-api#2]
Api video streaming URL automatic put the zero last point

**Comment by SailorSammyy** [comment]
> Api video streaming URL automatic put the zero last point 

I'm confused on what u mean by that?

**Comment by Zvudkdn** [comment]
Okay this is URL of call the API send data like this 
GET https://www044.anzeat.pro/streamhls/7a2215a44548be5c6a1a32acc5e913ed/ep.1.1713032808.m3u8 0
Automatic put the zero end URL
